In [9]:
import numpy as np
import pandas as pd

df = pd.read_csv('Thyroid_data.csv')
df.head()

,age,sex,on thyroxine,query on thyroxine,on antithyroid medication,sick,pregnant,thyroid surgery,I131 treatment,query hypothyroid,...,TT4 measured,TT4,T4U measured,T4U,FTI measured,FTI,TBG measured,TBG,referral source,label
0,41,F,f,f,f,f,f,f,f,f,...,t,125.0,t,1.14,t,109.0,f,0,SVHC,negative
1,23,F,f,f,f,f,f,f,f,f,...,t,102.0,f,0.00,f,0.0,f,0,other,negative
2,46,M,f,f,f,f,f,f,f,f,...,t,109.0,t,0.91,t,120.0,f,0,other,negative
3,70,F,t,f,f,f,f,f,f,f,...,t,175.0,f,0.00,f,0.0,f,0,other,negative
4,70,F,f,f,f,f,f,f,f,f,...,t,61.0,t,0.87,t,70.0,f,0,SVI,negative

In [10]:
# Open Labels
labels = df['label'].values

print(len(labels))

count = 0
for i in labels:
    if i == "negative":
        count += 1
print(count)

2800
2723

In [11]:
# Print unique values of each column
for i in df.columns:
    print(i, df[i].unique())

age [ 41  23  46  70  18  59  80  66  68  84  67  71  28  65  42  63  51  81
  54  55  60  25  73  34  78  37  85  26  58  64  44  48  61  35  83  21
  87  53  77  27  69  74  38  76  45  36  22  43  72  82  31  39  49  62
  57   1  50  30  29  75  19   7  79  17  24  15  32  47  16  52  33  13
  10  89  56  20  90  40  88  14  86  94  12   4  11   8   5 455   2  91
   6   0  93  92]
sex ['F' 'M' '0']
on thyroxine ['f' 't']
query on thyroxine ['f' 't']
on antithyroid medication ['f' 't']
sick ['f' 't']
pregnant ['f' 't']
thyroid surgery ['f' 't']
I131 treatment ['f' 't']
query hypothyroid ['f' 't']
query hyperthyroid ['f' 't']
lithium ['f' 't']
goitre ['f' 't']
tumor ['f' 't']
hypopituitary ['f' 't']
psych ['f' 't']
TSH measured ['t' 'f']
TSH [1.30e+00 4.10e+00 9.80e-01 1.60e-01 7.20e-01 3.00e-02 0.00e+00 2.20e+00
 6.00e-01 2.40e+00 1.10e+00 2.80e+00 3.30e+00 1.20e+01 1.20e+00 1.50e+00
 6.00e+00 2.10e+00 1.00e-01 8.00e-01 1.90e+00 3.10e+00 2.00e-01 1.30e+01
 3.00e-01 3.50e-02 2.50e+00 5.00e-01 1.70e+00 7.30e+00 1.80e+00 2.60e-01
 4.50e+01 5.40e+00 9.90e-01 2.50e-01 9.20e-01 1.50e-01 6.40e-01 1.00e+00
 4.00e-01 2.00e+00 2.60e+00 1.48e+01 1.50e+01 1.90e+01 2.00e-02 3.00e+00
 2.90e+00 3.20e+00 9.00e+00 1.60e+00 4.30e+00 5.00e-03 3.10e-01 6.10e-01
 5.00e-02 7.80e+00 1.60e+02 2.50e-02 1.40e+00 1.00e-02 8.80e+00 1.51e+02
 4.00e-02 3.90e+00 9.40e+00 2.70e+00 2.30e+00 9.40e-01 4.50e-02 3.50e+00
 8.80e-01 8.00e-02 4.50e+00 6.80e-01 7.00e-01 6.70e-01 2.70e+01 6.10e+00
 7.50e-01 5.50e-01 2.60e+01 5.20e+00 7.70e-01 7.00e-02 9.00e-01 1.14e+01
 1.43e+02 4.50e-01 5.70e-01 6.50e-01 1.50e-02 1.60e+01 1.08e+02 8.30e-01
 9.20e+00 8.60e+01 6.20e-01 5.90e-01 9.10e+00 5.90e+00 5.20e+01 3.30e-01
 3.10e+01 5.80e+00 2.80e-01 5.10e+01 6.30e+00 4.40e+00 9.60e+00 3.40e+00
 9.00e-02 2.40e+01 7.60e-01 4.20e+01 2.50e+01 1.00e+01 4.60e+00 8.60e+00
 6.60e-01 6.20e+00 7.90e-01 2.80e+01 8.60e-01 9.70e+00 8.40e-01 1.70e+01
 1.80e+01 5.50e+01 1.40e+01 3.70e+00 8.70e-01 6.70e+00 7.40e-01 7.60e+00
 6.50e-02 2.90e-01 3.70e-01 8.00e+00 1.10e+01 4.80e-01 4.40e+01 7.90e+00
 5.00e+00 7.20e+00 8.90e-01 9.30e-01 9.70e-01 1.20e-01 6.40e+00 3.30e+01
 8.50e-01 7.10e+00 7.30e-01 1.99e+02 8.20e+00 1.88e+02 2.20e-01 9.80e+01
 2.20e+01 6.60e+00 5.10e+00 6.00e-02 4.20e-01 3.80e+00 3.50e+01 4.00e+00
 7.80e-01 6.30e-01 5.20e-01 6.00e+01 4.30e-01 5.60e+00 6.90e+00 3.60e+00
 2.90e+01 3.80e-01 4.90e+00 4.10e-01 9.90e+00 7.50e+00 3.40e+01 6.50e+00
 4.70e+00 1.03e+02 9.50e-01 1.40e-01 3.50e-01 4.20e+00 8.10e-01 5.40e-01
 5.80e-01 8.90e+00 5.50e+00 3.40e-01 9.30e+00 1.30e-01 5.40e+01 3.90e-01
 8.30e+00 4.78e+02 2.10e+01 6.80e+00 3.20e-01 2.30e-01 2.40e-01 8.10e+00
 9.10e-01 5.30e+00 1.00e+02 2.70e-01 1.01e+00 5.80e+01 4.10e+01 1.83e+02
 1.84e+01 4.70e-01 1.70e-01 1.21e+01 1.90e-01 8.20e-01 4.30e+01 4.40e-01
 7.00e+01 7.70e+00 8.40e+00 6.90e-01 8.50e+00 2.10e-01 8.20e+01 5.50e-02
 9.60e-01 7.10e-01 3.80e+01 3.60e-01 9.80e+00 7.00e+00 4.60e-01 1.11e+01
 3.90e+01 7.60e+01 5.70e+00 3.20e+01 1.26e+02 2.64e+01 5.30e-01 4.90e-01
 3.60e+01 1.78e+02 1.45e+02 4.70e+01 4.80e+00 1.03e+01 8.90e+01 7.40e+00
 4.72e+02 5.10e-01 1.16e+02 6.10e+01 9.90e+01 4.60e+01 7.80e+01 4.68e+02]
T3 measured ['t' 'f']
T3 [ 2.5   2.    0.    1.9   1.2   0.6   2.2   1.6   3.8   1.7   1.8   2.6
  2.1   0.3   5.5   1.4   3.1   1.5   2.3   2.4   2.7   0.9   1.    2.8
  2.9   0.8   1.3   0.4   3.3   3.5   3.4   1.1   4.2   3.7   3.    0.7
  4.8   4.3   0.05  3.2   5.4   4.    0.5   0.2   3.6   5.2   5.    6.
  5.3   3.9   4.6   4.5   7.3   4.7   6.7   4.1   6.1   0.1   4.9  10.6
  5.1   7.    6.2   4.4   7.1 ]
TT4 measured ['t' 'f']
TT4 [125.  102.  109.  175.   61.  183.   72.   80.  123.   83.  115.  152.
 171.   97.   99.   70.  117.  121.  130.  108.  104.  134.  199.   57.
 129.  113.  119.   84.   81.   95.   66.  101.  147.  120.   69.    0.
  39.   87.   63.  133.   86.  163.  162.  103.   96.  151.  112.   82.
 138.   71.   77.   93.  107.  237.  110.   67.   88.  160.  118.  136.
 114.  116.   94.  161.   11.   32.  124.  137.   92.  135.  105.  150.
 126.  146.   91.  217.  141.  159.  122.  100.  111.  140.  205.  225.
  85.   90.   74.  219.  127.  132.  128.  106.  144.  131.   56.   79.
 142.   98.  177.  139.   78.  189.  180.   73.  145.  184.   38.  156.
  75.  148.   14.   76.   54.   58.   27.   65.  193.   13.  143.   12.
  64.  257.  164.   59.  167.   18.   41.  176.   37.   33.   44.   45.
 154.  174.  203.  244.   62.  158.   60.  187.  250.  181.  157.  223.
 272.  166.  213.  235.   10.   68.  231.  191.   48.    5.8 169.  149.
 210.   40.  155.  232.   42.  204.  430.  198.  230.   15.  170.  165.
  47.  168.  194.   89.   52.  179.  192.  172.    4.8  50.  182.  197.
 214.  246.  196.  207.   19.  153.   22.   46.  200.   35.  226.  201.
 233.  206.   31.  255.  178.  239.  195.    6.   36.    2.    3.  289.
 240.  209.   43.   34.  252.   29.  263.  301.   23.  188.  211.  253.
  21.  173. ]
T4U measured ['t' 'f']
T4U [1.14  0.    0.91  0.87  1.3   0.92  0.7   0.93  0.89  0.95  0.99  1.13
 0.86  0.96  0.94  0.9   1.02  1.05  0.62  1.06  1.55  0.83  1.09  1.07
 1.27  0.76  1.16  1.    0.56  0.81  0.68  0.78  0.85  1.35  1.15  0.82
 1.03  1.58  0.79  1.17  0.71  0.72  0.88  1.11  1.2   1.1   1.33  0.77
 1.24  0.53  1.44  1.63  1.51  1.42  1.23  1.01  0.98  0.61  1.12  1.43
 1.25  1.41  1.68  0.97  0.84  0.8   1.04  0.73  1.08  1.26  1.46  1.29
 1.34  1.66  1.21  1.19  0.75  0.52  1.83  1.39  1.5   1.93  1.18  0.74
 0.58  1.82  0.6   1.67  1.22  0.66  0.67  1.31  0.54  1.77  1.59  1.97
 1.69  1.38  1.28  1.4   0.69  0.65  1.74  2.03  1.73  1.65  1.36  1.52
 0.57  1.53  1.84  1.57  1.75  1.32  1.37  0.64  1.79  1.8   0.48  1.71
 1.62  1.76  1.56  1.48  0.59  0.31  1.94  2.12  1.47  0.63  0.944 0.49
 1.88  0.5   0.38  1.49  0.41  1.61  1.7  ]
FTI measured ['t' 'f']
FTI [109.    0.  120.   70.  141.   78.  115.  132.   93.  121.  153.  151.
 107.  119.   87.   81.  104.  130.  106.  116.  131.  190.   92.  102.
  76.   98.   90.   61.   94.  129.   95.   91.   33.  113.  148.  140.
 171.  155.  186.  122.  136.  110.  111.   97.   72.  100.   88.   67.
  84.  103.  135.  203.  112.  117.  180.  142.  145.  156.   96.  134.
   8.9  60.  139.   41.   99.   89.  146.  124.  105.   85.  157.  143.
  71.  221.   28.  108.  137.   83.   74.  170.   65.  101.  127.  274.
 154.  114.   62.   86.  126.  125.   64.  172.  162.   79.  118.   73.
 152.  163.  149.   14.   51.  165.   77.   32.   69.   80.   11.   54.
 164.  123.  144.   10.  214.  200.  160.   53.   16.  138.  169.   56.
  47.  133.   43.   68.  179.  224.  220.   82.  362.  182.   75.   66.
 161.   57.   58.  312.   63.  128.  147.  158.  281.  207.  216.  251.
 194.   46.    7.   42.  174.  395.  185.   13.  201.   48.  173.  167.
 188.  150.  235.  175.  159.    5.4 189.   59.  166.   34.  228.  232.
 217.  177.  176.  195.  219.   17.  210.  168.  205.   39.  187.   50.
 349.   52.  206.  253.  242.  244.  213.  178.  247.  215.  198.   19.
 237.   37.    7.6  24.    2.    3.  191.  223.    9.   29.  222.  204.
  26.  218.  197.   49.  209.  183. ]
TBG measured ['f']
TBG [0]
referral source ['SVHC' 'other' 'SVI' 'STMW' 'SVHD']
label ['negative' 'hyperthyroid' 'T3 toxic' 'goitre']